export const Constants = {
  coinPayoff: 1.0,
  daggerPayoff: 4.0,
  criticalDaggerPayoff: 1e7,
  pathSafetyRelativeDangerScale: 0.5,
  pathSafetyRelativeDangerThreshold: 3.5,
  pathSafetyDangerousMultiplier: 0.1,
  safetyPayoff: 10000.0,
  killPayoff: 4.0,
  bonusPayoff: 4.0,
  daggerLife: 15,
  bonusLife: 15,
  daggerEquippedLife: 15,
  bonusEquippedLife: 30,
  safetyThreshold: 4,
  safetyIterationDepth: 6,
  defaultVisibilityRadius: 5,
}
